name: Gitea Actions Demo
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [push]

jobs:
  Explore-Gitea-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Starting runner
        uses: echo "Runner is started."
      - name: Check out repository ${{ gitea.repository }}
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          ls ${{ gitea.workspace }}
      - name: Pipeline status
        run: echo "🍏 This job's status is ${{ job.status }}."

