name: Gitea Actions Demo
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [push]

jobs:
  Explore-Gitea-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: ls ${{ gitea.workspace }}
      - name: List images 2
        run: docker image ls
      - name: Build docker image
        run: |
          docker build -t modbus-to-mqtt --target base ${{ gitea.workspace }} && \\
          docker build -t modbus-to-mqtt --target test ${{ gitea.workspace }} 
      - name: List images 2
        run: docker image ls
