name: Gitea Actions Demo
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [push]

jobs:
  Build-docker-images:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: ls ${{ gitea.workspace }}
      - name: Build docker images
        run: |
          docker build -t modbus-to-mqtt-${{ github.run_number }} --target base ${{ gitea.workspace }} --no-cache && \
          docker build -t modbus-to-mqtt-test-${{ github.run_number }} --target test ${{ gitea.workspace }} --no-cache 
      - name: Black syntax test
        run: docker run modbus-to-mqtt-test-${{ github.run_number }} python3 -m black . --check
      - name: Mypy type test
        run: docker run modbus-to-mqtt-test-${{ github.run_number }} python3 -m mypy .

      - name: Remove docker images
        run: docker image rm modbus-to-mqtt-${{ github.run_number }} modbus-to-mqtt-test-${{ github.run_number }} --force
        if: always()

  Release-image:
    runs-on: ubuntu-latest
    needs: ["Build-docker-images"]
    if: gitea.ref == 'refs/heads/main'
    steps:
      - name: test
        uses: echo "123"
