name: Build docker image
run-name: ${{ github.actor }} is testing out github Actions 🚀
on: [push]

jobs:
  Build-docker-images:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build docker images
        run: |
          docker build -t modbus-to-mqtt-test --target test ${{ github.workspace }} --no-cache 
      - name: Black syntax test
        run: docker run modbus-to-mqtt python3 -m black . --check
      - name: Mypy type test
        run: docker run modbus-to-mqtt python3 -m mypy .

  Release-image:
    runs-on: ubuntu-latest
    needs: ["Build-docker-images"]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.TOKEN}}

      - name: 'Build Inventory Image'
        run: |
          docker build . --tag ghcr.io/${{github.actor}}/modbus-to-mqtt:latest --target base ${{ github.workspace }}
          docker push ghcr.io/${{github.actor}}/modbus-to-mqtt:latest
